ext txt = nvim "$@"

# show hidden files
set show_hidden true

# preview images
set preview_images_method iterm2
set preview_images true

# be aware of git
set vcs_aware false

# put outline on columns
set draw_borders both
